### ISSUE TITLE
Tag labelling

### ISSUE THREAD

**Issue by vladsamoylik** [mr-karan/aws-dc-exporter#2]
Good day! I have a couple of questions:
1. How can I receive information from two or more regions at the same time by one aws-dc-exporter installation?
2. How can I request the values of aws_dc_connections and aws_dc_bgp_peers labels.

**Comment by mr-karan** [comment]
1. You can do that by creating multiple jobs for different regions. Here's an example:

```
[[app.jobs]]
name="region-a" # Unique Job Name
[app.jobs.aws_creds]
region="ap-south-1" # Required.
[[app.jobs]]
name="region-b" # Unique Job Name
[app.jobs.aws_creds]
region="-us-west-1" # Required.
```

2. Sorry, I didn't get you. You could make queries with `aws_dc_connections{}` / `aws_dc_bgp_peers{}` on PromQL. If you wanna see all the labels that are exported, just make this empty query on Prometheus, it'll show a list of labels.

**Comment by vladsamoylik** [comment]
Thanks! I got an exhaustive answer to the first question, and it works. But with regard to the second, not everything is so simple. Our task is to match bgp_peer_id with aws_dc_virtual_interfaces in order to exclude the firing of an alert on bgp_peer_id for those connections that do not work as they are in configuration mode.

Unfortunately, I cannot get the following tree by giving a promql request: aws_dc_virtual_interfaces> bgp_peer_id.
If this is a long time for you, then I can try to increase this functionality on my own and send you a fix.

**Comment by vladsamoylik** [comment]
And yet, so I corrected the expression for the alert manager, the ones described for you do not work correctly for me:

```
  - alert: AWSDCConnectionDown
    expr: count(aws_dc_connections{conn_state="down", conn_name!~".*dev"}) by (conn_id, conn_name) > 0
    for: 0m
    labels:
      severity: 4
    annotations:
      title: "AWS DC Connection down (Connection name:  {{ $labels.conn_id }}, Connection ID: {{ $labels.conn_id }})."
  - alert: AWSBGPPeerDown
    expr: count(aws_dc_bgp_peers{bgp_status="down"}) by (bgp_peer_id) > 0
    for: 0m
    labels:
      severity: 4
    annotations:
      title: "AWS DC BGP Peer down (Peer ID: {{ $labels.bgp_peer_id }})."

```
Thanks!
